name: "family_board"

services:
  app:
    build:
      context: Frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${WEB_PORT}:8080"

  backend:
    build:
      context: Backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      Jwt__key: ${Jwt_key}
      ConnectionStrings__familyBoard: ${Connection_string}
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:18
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./Backend/Database-creation/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "family_board"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  postgres_data:
  